#!/bin/bash
clear
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
apt clean && apt autoclean && apt full-upgrade -y
sleep 2s
wget https://raw.githubusercontent.com/zxlordxz/SSHVIP/main/script/install; chmod 777 ./install; ./install

