#!/bin/bash

clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                $date"
figlet   ' BADVPN-PRO ' | lolcat
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;37mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "\033[1;33m \033[1;33m⚠️ INSTALAR BADVPN ANTES DE ABRIR TODAS AS PORTAS ⚠️ \033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m01\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR BADVPN(7300 PADRÃO) $var_sks1 \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m02\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR BADVPN ARM(7300 PADRÃO) $var_sks1 \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m03\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7296) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m04\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7297) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m05\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7298) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m06\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7299) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m07\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7200) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m08\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7400) \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m09\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN(7500) \033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m10\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR TODAS AS PORTAS BADVPN \033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m11\033[1;34m]\033[1;37m ➩  \033[1;33mMONITOR DE PORTAS BADVPN-UDP \033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m00\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR AO MENU PRINCIPAL\033[0m"
    echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
    echo -ne "\033[1;31m╚╣\033[1;32m INFORME UMA OPÇÃO \033[1;37m: " ; read x

case "$x" in

    1 | 01)
      clear
      badpro
echo "================================================"
;;
    2 | 02)
    install dos2unix -y /dev/null
    wget https://raw.githubusercontent.com/BGXSJYRABJE/hdisbsi/main/badvpn/badvpn.sh /dev/null
    chmod 777 badvpn.sh
    ./badvpn.sh
echo "================================================"
;;
   3 | 03)
      echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7296 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 1000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   4 | 04)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7297 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   5 | 05)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7298 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   6 | 06)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7299 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   7 | 07)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   8 | 08)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7400 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   9 | 09)
       echo -e "\033[1;32mINICIANDO BADVPN PRO... \033[0m\n"
      screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7500 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
      sleep 3
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
;;
   10)
   echo -e "\033[1;32mINICIANDO TODAS AS PORTAS BADVPN PRO... \033[0m\n"
sleep 6
screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7295 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7296 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7297 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7298 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7299 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7400 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000

screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7500 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
echo -e "\033[1;32mPORTA BADVPN PRO ATIVADO COM SUCESSO\033[1;33m"
sleep 4
echo "================================================"
 ;;
     11)
        clear
        badvpn
echo "================================================"
 ;;
     12)
        menub
echo "================================================"
;;
    0 | 00)
        clear
        menu
echo "================================================"
;;

*)
        echo "Opção inválida!"
esac
done

}
menu
