#!/bin/bash
    clear
    echo -e "\033[46;1;37m                    MENU BADVPN                    \033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
	if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e " \033[47;1;30mATIVE O BADVPN PRO/ARM PRIMEIRO, ANTES DE ATIVAR TODAS AS PORTAS \033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[47;1;30mBADVPN PRO $stsu\033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[41;1;37mBADVPN ARM\033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[47;1;30mATIVAR TODAS AS PORTAS\033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			badpro
			;;
			2 | 02)
			badvpn
			;;
			3 | 03)
			echo -e "\033[1;32mATIVANDO TODAS AS PORTAS... \033[0m\n"
    sleep 6
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7000 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7100 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7400 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7500 --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
	sleep 2
            echo -e "\033[1;32mPORTAS ATIVADO COM SUCESSO\033[1;33m"
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	menub
}
