#!/bin/bash

clear
_diskText=$(df -h | awk '$NF=="/"{printf "%d/%dGB + (%s)\n", $3,$2,$5}')
_swap1=$(free -h | grep -i swap | awk {'print $2'})
swap4=$(free | awk '/Swap/{printf("%.1f%"), $3/($2+.000000001)*100}';)
clear
figlet   ' MEMORIA 
   SWAP' | lolcat
echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;36m    SWAP INSTALADO \033[1;37m ($_swap1) \033[1;31m║\033[1;36m ESPAÇO TOTAL \033[1;37m ($_diskText"
echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m01\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR MEMORIA SWAP OU ALTERAR O VALOR INSTALADO"
echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m02\033[1;34m]\033[1;37m ➩  \033[1;33mREMOVER MEMORIA SWAP INSTALADO"
echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
echo -e "\033[01;31m  \033[1;31m\033[1;34m[\033[1;37m00\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR AO MENU PRINCIPAL"
echo -e "\033[1;31m════════════════════════════════════════════════════════════\033[0m"
echo -ne "\033[1;31m╚╣\033[1;32m INFORME UMA OPÇÃO \033[1;37m: " ; read x
			case $x in

			1 | 01)
                        clear
			echo -e "\E[44;1;37m            MEMORIA VIRTUAL              \E[0m"
			echo ""
			echo -ne "\033[1;33mQUANTOS GIGAS DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mGIGAS INVALIDO!"
					sleep 2
					clear
					swapmemory
				}
            echo ""
			echo -e "\033[1;32mINICIANDO MEMORIA VIRTUAL \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL ATIVADO COM SUCESSO\033[1;33m"
            sleep 2
			swapmemory
                        ;;
                        2 | 02)
            clear
			echo -e "\E[44;1;37m            DESATIVANDO MEMORIA VIRTUAL              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL DESATIVADO COM SUCESSO!\033[1;33m"
			sleep 2
			swapmemory
                        ;;
                        0 | 00)
			echo ""
			echo -e "\033[1;31mRetornando...\033[0m"
			sleep 1
			menu
                        ;;
		        *)
			echo ""
			echo -e "\033[1;31mOpcao invalida !\033[0m"
                        esac
                        done
		
}
swapmemory
