#!/bin/bash
    clear
    echo -e "\033[46;1;37m                  WEBSOCKET SECURITY                   \033[0m"
    echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e " \033[47;1;30mINSTALE PRIMEIRO ANTES DE ATIVAR O WEB-SECURITY \033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 \033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR\033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
	echo -e " \033[47;1;30mATIVE APENAS UM PARA NAO OCORRER ERRO \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 \033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR (PORTA 80)\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 \033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR (PORTA 8080)\033[0m"
	echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 04 \033[1;34m]\033[1;37m ➩  \033[1;33mDESATIVAR PORTA\033[0m"
    echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 \033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[0;36m════════════════════════════•⊱✦⊰•════════════════════════════\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			clear
			wget http://worldofdragon.us.eu.org/wssecu/wssecury.sh && dos2unix wssecury.sh && chmod 777 wssecury.sh && ./wssecury.sh && screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:8080 -msg=Security
			;;
			2 | 02)
			clear
			screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:80 -msg=Security
			;;
			3 | 03)
			clear
			screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:8080 -msg=Security
			;;
			4 | 04)
			clear
			screen -R novows
			;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	websecurity
}
